;Bear Traps
0x14F879~Wyrmstooth.esp|Places a trap when dropped, triggers for <font color="#FFFFFF">20</font> points of damage when stepped on.|999
0x803~WTCraftableBearTrap.esp|Places a trap when dropped, triggers for <font color="#FFFFFF">30</font> points of damage when stepped on.|999
0x802~WTCraftableBearTrap.esp|Places a trap when dropped, triggers for <font color="#FFFFFF">40</font> points of damage when stepped on.|999
0x806~WTCraftableBearTrap.esp|Places a trap when dropped, triggers for <font color="#FFFFFF">45</font> points of damage when stepped on.|999
;Essence Extractor
0x1A31C~Skyrim.esm|Harvests elven blood.|999
;Lucien's Resonant Sphere
0x4E9CB8~Lucien.esp|Tracks Lucien's current location.|999
;Torches
0x1d4ec~Skyrim.esm|Lights and warms the surrounding area for <font color="#FFFFFF">240</font> seconds.|999
0x36343~Skyrim.esm|Lights and warms the surrounding area for <font color="#FFFFFF">240</font> seconds.|999